import React from 'react'
import {Box} from "@chakra-ui/react"
import RecomendationList from './RecomendationList'


const Recommendations = () => {

    const rec =  [
          {
            "id": "805535e1de5a4c7991f4f323e82ce9e7",
            "rss": "https://bryankramer.libsyn.com/rss",
            "type": "episodic",
            "email": "bryan.kramer@purematter.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9icnlhbmtyYW1lci5saWJzeW4uY29tL3Jzcw==",
              "spotify_url": "",
              "youtube_url": "",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "bryankramer",
              "facebook_handle": "",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/the-bryan-kramer-show-bryan-kramer-Br0M_IayKc3-0SCl91ZT-bU.1400x1400.jpg",
            "title": "The Bryan Kramer Show",
            "country": "United States",
            "website": "http://bryankramer.libsyn.com/podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              67,
              88,
              90,
              93,
              97
            ],
            "itunes_id": 1078655111,
            "publisher": "Bryan Kramer",
            "thumbnail": "https://production.listennotes.com/podcasts/the-bryan-kramer-show-bryan-kramer-E7o80typv_b-0SCl91ZT-bU.300x300.jpg",
            "is_claimed": false,
            "description": "Join us as Bryan Kramer deconstructs human behavior and digs deep to share tactics, tools and tricks you can use every day to help you reach peak performance. In each show, Bryan interviews high-profile guests hitting consistent home runs in business, entrepreneurialism marketing and social. Bryan is a TED speaker, USA Today best-selling author, and CEO who consults Fortune 500 clients such as IBM, Cisco, NFL, Harvard University and NASA. He's known for his books Human to Human, #H2H and Shareology. Forbes calls him a \"Zen master to digital marketers.\"",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 35,
            "total_episodes": 64,
            "listennotes_url": "https://www.listennotes.com/c/805535e1de5a4c7991f4f323e82ce9e7/",
            "audio_length_sec": 1695,
            "explicit_content": false,
            "latest_episode_id": "99eb35864e2242a480f4709ded9471b5",
            "latest_pub_date_ms": 1502287200000,
            "earliest_pub_date_ms": 1453246535000,
            "update_frequency_hours": 327,
            "listen_score_global_rank": "3%"
          },
          {
            "id": "7060b5d48b3440ba9668f9af2a90fa7f",
            "rss": "https://www.spreaker.com/show/4920844/episodes/feed",
            "type": "episodic",
            "email": null,
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy80ZjJjNjZmMC9wb2RjYXN0L3Jzcw==",
              "spotify_url": "https://open.spotify.com/show/62soqGPhnYJBRrP2vSAk6b",
              "youtube_url": "",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "",
              "facebook_handle": "",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/the-tim-ferriss-show-5-minute-podcast-mpqMa73u08D-mYx8LcSkhz1.1400x1400.jpg",
            "title": "The Tim Ferriss Show | 5 minute podcast summaries",
            "country": "United States",
            "website": "https://www.spreaker.com/show/the-tim-ferriss-show-5-minute-podcast-su?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              111,
              181,
              67
            ],
            "itunes_id": 1556286643,
            "publisher": "5 minute podcast summaries",
            "thumbnail": "https://production.listennotes.com/podcasts/the-tim-ferriss-show-5-minute-podcast-XMuN8q2Jorb-mYx8LcSkhz1.300x300.jpg",
            "is_claimed": false,
            "description": "5 minute summaries of The Tim Ferriss Show's podcast episodes. Get the best insights and ideas in much less time, more at owltail.com<br /><br />Written summaries: <a href=\"https://www.owltail.com/summaries/75553-the-tim-ferriss-show\" rel=\"noopener\">https://www.owltail.com/summaries/75553-the-tim-ferriss-show</a><br /><br />Other podcast summaries in Apple Podcasts: <a href=\"http://bit.ly/5-min-summaries\" rel=\"noopener\">http://bit.ly/5-min-summaries</a><br /><br />Other podcast summaries In other apps, search 'podcast summaries'.<br /><br />Tim Ferriss is a self-experimenter and bestselling author, best known for The 4-Hour Workweek, which has been translated into 40+ languages. Newsweek calls him \"the world's best human guinea pig,\" and The New York Times calls him \"a cross between Jack Welch and a Buddhist monk.\" In this show, he deconstructs world-class performers from eclectic areas (investing, chess, pro sports, etc.), digging deep to find the tools, tactics, and tricks that listeners can use.",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 35,
            "total_episodes": 12,
            "listennotes_url": "https://www.listennotes.com/c/7060b5d48b3440ba9668f9af2a90fa7f/",
            "audio_length_sec": 221,
            "explicit_content": false,
            "latest_episode_id": "9163fe8fdfc34710af8d41b575023e07",
            "latest_pub_date_ms": 1625881044000,
            "earliest_pub_date_ms": 1619229600011,
            "update_frequency_hours": 165,
            "listen_score_global_rank": "3%"
          },
          {
            "id": "d1344e580523433e9e7b6d3d17579c68",
            "rss": "https://feeds.acast.com/public/shows/eddbcc04-6cf8-4a7b-8bf7-f29cb306da8c",
            "type": "episodic",
            "email": null,
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5hY2FzdC5jb20vcHVibGljL3Nob3dzL2VkZGJjYzA0LTZjZjgtNGE3Yi04YmY3LWYyOWNiMzA2ZGE4Yw==",
              "spotify_url": "",
              "youtube_url": "",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "",
              "facebook_handle": "",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/the-guinea-pig-the-guinea-pig-podcast-f71pCJnAd8Q-bpDvSg1QWR4.1400x1400.jpg",
            "title": "The Guinea Pig",
            "country": "United States",
            "website": null,
            "language": "English",
            "genre_ids": [
              90,
              107,
              111,
              67
            ],
            "itunes_id": 1453993716,
            "publisher": "The Guinea Pig Podcast",
            "thumbnail": "https://production.listennotes.com/podcasts/the-guinea-pig-the-guinea-pig-podcast-eQwm9xXzlPv-bpDvSg1QWR4.300x300.jpg",
            "is_claimed": false,
            "description": "Leading surgeon and founder of cult brand MZ SKIN, Dr Maryam Zamani and ex-Vogue editor-at-Large, Fiona Golfar present The Guinea Pig podcast!Fiona and Maryam share their honest opinions and hilarious real-life experiences and give essential safety advice to those considering any kind of aesthetic procedure.For adults only, this bi-weekly podcast covers the latest aesthetic treatment reviews by the resident guinea pig, Fiona Golfar, supported by necessary medical advice and insights from Dr Maryam Zamani.Fiona tries the treatments - so you don’t have to - allowing the listener to decide for themselves once they are armed with the necessary knowledge, questions to ask and potential risks. Maryam and Fiona chat openly and candidly about products and procedures aided by experts & high-profile friends to offer advice and insights to anyone considering a treatment.So if you, or someone you know is thinking of changing their moisturiser, dealing with tired looking eyes, or even having a neck-lift, The Guinea Pig is here to help you!<br /><hr><p style='color:grey; font-size:0.75em;'> Hosted on Acast. See <a style='color:grey;' target='_blank' rel='noopener noreferrer' href='https://acast.com/privacy'>acast.com/privacy</a> for more information.</p>",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 40,
            "total_episodes": 70,
            "listennotes_url": "https://www.listennotes.com/c/d1344e580523433e9e7b6d3d17579c68/",
            "audio_length_sec": 1715,
            "explicit_content": true,
            "latest_episode_id": "7ce4a41ab7034fb2936646236b392dc0",
            "latest_pub_date_ms": 1613008800000,
            "earliest_pub_date_ms": 1550841504069,
            "update_frequency_hours": 319,
            "listen_score_global_rank": "1.5%"
          },
          {
            "id": "f9d5885d7cf7485d891e82dea3186640",
            "rss": "https://rss.art19.com/how-i-built-this",
            "type": "episodic",
            "email": "iwonder@wondery.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9yc3MuYXJ0MTkuY29tL2hvdy1pLWJ1aWx0LXRoaXM=",
              "spotify_url": "https://open.spotify.com/show/6E709HRH7XaiZrMfgtNCun",
              "youtube_url": "",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "HowIBuiltThis",
              "facebook_handle": "howibuiltthis",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/how-i-built-this-with-guy-raz-guy-raz-wondery-I8nbimW4uEZ-UC0qH23iP9T.1400x1400.jpg",
            "title": "How I Built This with Guy Raz",
            "country": "United States",
            "website": "https://wondery.com/shows/how-i-built-this/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              157,
              90,
              173,
              94,
              106,
              127,
              93,
              67,
              171
            ],
            "itunes_id": 1150510297,
            "publisher": "Guy Raz | Wondery",
            "thumbnail": "https://production.listennotes.com/podcasts/how-i-built-this-with-guy-raz-guy-raz-wondery-6hPxKdwGUe0-UC0qH23iP9T.300x300.jpg",
            "is_claimed": false,
            "description": "\n      <p>Guy Raz interviews the world’s best-known entrepreneurs to learn how they built their iconic brands. In each episode, founders reveal deep, intimate moments of doubt and failure, and share insights on their eventual success. <em>How I Built This </em>is a master-class on innovation, creativity, leadership and how to navigate challenges of all kinds.</p><p>New episodes on Mondays and Thursdays for free. Listen 1-week early and to all episodes ad-free with Wondery+ or Amazon Music with a Prime membership or Amazon Music Unlimited subscription.</p><p>Get your How I Built This merch at <a href=\"https://wonderyshop.com/pages/howibuiltthis ?utm_source=hibt-podcast&utm_medium=referral&utm_campaign=hibt-description\" rel=\"noopener noreferrer\" target=\"_blank\">WonderyShop.com/HowIBuiltThis</a></p><p><br></p>\n    ",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 83,
            "total_episodes": 557,
            "listennotes_url": "https://www.listennotes.com/c/f9d5885d7cf7485d891e82dea3186640/",
            "audio_length_sec": 2989,
            "explicit_content": false,
            "latest_episode_id": "ab7c87a151b94305bd6805882b1185e9",
            "latest_pub_date_ms": 1694664600000,
            "earliest_pub_date_ms": 1472828160550,
            "update_frequency_hours": 78,
            "listen_score_global_rank": "0.01%"
          },
          {
            "id": "fe6864628066420c8103c94e91e72eb3",
            "rss": "https://anchor.fm/s/f39a864/podcast/rss",
            "type": "episodic",
            "email": "justin.schnell@vaynermedia.com",
            "extra": {
              "url1": "https://medium.com/@garyvee",
              "url2": "https://www.snapchat.com/add/garyvee",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cDovL2Fza2dhcnl2ZWUuZ2FyeXZlZS5saWJzeW5wcm8uY29tL3Jzcw==",
              "spotify_url": "https://open.spotify.com/show/6SZVsPIxPfVs6aavqM1peY",
              "youtube_url": "https://www.youtube.com/user/garyvaynerchuk",
              "linkedin_url": "https://www.linkedin.com/in/garyvaynerchuk/",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "garyvee",
              "facebook_handle": "gary",
              "amazon_music_url": "https://music.amazon.com/podcasts/97113abf-5c18-4c7e-8d2b-efcf161f4848/the-garyvee-audio-experience",
              "instagram_handle": "garyvee"
            },
            "image": "https://production.listennotes.com/podcasts/the-garyvee-audio-experience-gary-vaynerchuk-gNfBoYH9uUy-X0Dfm7O_o3y.1400x1400.jpg",
            "title": "The GaryVee Audio Experience",
            "country": "United States",
            "website": "http://www.garyvaynerchuk.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              95,
              127,
              169,
              78,
              157,
              97,
              98,
              173,
              93,
              67,
              171
            ],
            "itunes_id": 928159684,
            "publisher": "Gary Vaynerchuk",
            "thumbnail": "https://production.listennotes.com/podcasts/the-garyvee-audio-experience-gary-vaynerchuk-U9oAGIlVtq6-X0Dfm7O_o3y.300x300.jpg",
            "is_claimed": false,
            "description": "Welcome to The GaryVee Audio Experience, hosted by entrepreneur, CEO, investor, content creator, and public speaker Gary Vaynerchuk. On this podcast you'll find a mix of the #AskGaryVee show episodes, keynote speeches on marketing and business, segments from my DAILYVEE video series, interviews and fireside chats I've given, as well as new and current thoughts I record originally for this audio experience!\n\n",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 80,
            "total_episodes": 2732,
            "listennotes_url": "https://www.listennotes.com/c/fe6864628066420c8103c94e91e72eb3/",
            "audio_length_sec": 1864,
            "explicit_content": true,
            "latest_episode_id": "4a26253059ed4e42a67c02c6d55fe487",
            "latest_pub_date_ms": 1694761200000,
            "earliest_pub_date_ms": 1412179202542,
            "update_frequency_hours": 24,
            "listen_score_global_rank": "0.01%"
          },
          {
            "id": "9f6ee51adfb046cc9936490abd2666ce",
            "rss": "https://feeds.simplecast.com/AAvup9Zz",
            "type": "episodic",
            "email": "podcast@schoolofgreatness.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9BQXZ1cDlaeg==",
              "spotify_url": "https://open.spotify.com/show/07GQhOZboEZOE1ysnFLipT",
              "youtube_url": "https://www.youtube.com/user/lewishowes",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "lewishowes",
              "facebook_handle": "lewishowes",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/the-school-of-greatness-lewis-howes-Ggb9PDwVr63-H1zdqljixbp.1400x1400.jpg",
            "title": "The School of Greatness",
            "country": "United States",
            "website": "https://www.stitcher.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              77,
              78,
              90,
              89,
              97,
              94,
              171,
              93,
              181,
              111,
              91,
              67,
              88
            ],
            "itunes_id": 596047499,
            "publisher": "Lewis Howes",
            "thumbnail": "https://production.listennotes.com/podcasts/the-school-of-greatness-lewis-howes-jyfMSXd41U8-H1zdqljixbp.300x300.jpg",
            "is_claimed": false,
            "description": "Lewis Howes is a New York Times best-selling author, 2x All-American athlete, keynote speaker, and entrepreneur. The School of Greatness shares inspiring interviews from the most successful people on the planet—world-renowned leaders in business, entertainment, sports, science, health, and literature—to inspire YOU to unlock your inner greatness and live your best life.",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 78,
            "total_episodes": 1507,
            "listennotes_url": "https://www.listennotes.com/c/9f6ee51adfb046cc9936490abd2666ce/",
            "audio_length_sec": 3155,
            "explicit_content": false,
            "latest_episode_id": "176c41a458714823abfc008d1b49c877",
            "latest_pub_date_ms": 1694761200000,
            "earliest_pub_date_ms": 1358928001491,
            "update_frequency_hours": 45,
            "listen_score_global_rank": "0.01%"
          },
          {
            "id": "a409b8bb93f44054a7be2d6b30843899",
            "rss": "https://entrepreneuronfire.libsyn.com/rss",
            "type": "episodic",
            "email": "John@EntrepreneurOnFire.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9lbnRyZXByZW5ldXJvbmZpcmUubGlic3luLmNvbS9yc3M=",
              "spotify_url": "https://open.spotify.com/show/25wgHxrQY2e7WNeV4UtECI",
              "youtube_url": "https://www.youtube.com/channel/UCXfzpliAfdjParawJljHo2g",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "johnleedumas",
              "facebook_handle": "johnleedumas1",
              "amazon_music_url": "https://music.amazon.com/podcasts/4728a7fc-731f-4b18-971b-85b0b8c2e784/entrepreneurs-on-fire",
              "instagram_handle": "johnleedumas"
            },
            "image": "https://production.listennotes.com/podcasts/entrepreneurs-on-fire-john-lee-dumas-of-DekxRsp0tNA-1WOhT7u6VQb.1400x1400.jpg",
            "title": "Entrepreneurs on Fire",
            "country": "United States",
            "website": "https://www.eofire.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              88,
              111,
              90,
              94,
              97,
              169,
              157,
              173,
              93,
              67,
              171
            ],
            "itunes_id": 564001633,
            "publisher": "John Lee Dumas of EOFire",
            "thumbnail": "https://production.listennotes.com/podcasts/entrepreneurs-on-fire-john-lee-dumas-of-o7xODP0r6-Q-1WOhT7u6VQb.300x300.jpg",
            "is_claimed": true,
            "description": "John Lee Dumas is the founder and host of the award winning podcast, Entrepreneurs On Fire. With over 100 million listens of his 3000+ episodes, JLD has turned Entrepreneurs On Fire into a media empire that generates over a million listens every month and 7-figures of NET annual revenue 8-years in a row. His first traditionally published book, The Common Path to Uncommon Success is the modern day version of Think and Grow Rich with a revolutionary 17-step roadmap to financial freedom and fulfillment. Learn more at UncommonSuccessBook.com",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 69,
            "total_episodes": 3473,
            "listennotes_url": "https://www.listennotes.com/c/a409b8bb93f44054a7be2d6b30843899/",
            "audio_length_sec": 1804,
            "explicit_content": false,
            "latest_episode_id": "de2a4259999646abb0f64f2898ad84b1",
            "latest_pub_date_ms": 1694766600000,
            "earliest_pub_date_ms": 1348297203456,
            "update_frequency_hours": 24,
            "listen_score_global_rank": "0.05%"
          },
          {
            "id": "499661f3589f42aaa1532673e0e0aedf",
            "rss": "https://rss.art19.com/smart-passive-income-podcast",
            "type": "episodic",
            "email": "podcasts@teamspi.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9yc3MuYXJ0MTkuY29tL3NtYXJ0LXBhc3NpdmUtaW5jb21lLXBvZGNhc3Q=",
              "spotify_url": "https://open.spotify.com/show/7wjv5MRCXWXImqTFhcufLy",
              "youtube_url": "https://www.youtube.com/user/smartpassiveincome",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "patflynn",
              "facebook_handle": "smartpassiveincome",
              "amazon_music_url": "https://music.amazon.com/podcasts/341282a1-cba9-4188-aa58-e09a51ccaa87/the-smart-passive-income-online-business-and-blogging-podcast",
              "instagram_handle": "patflynn"
            },
            "image": "https://production.listennotes.com/podcasts/the-smart-passive-income-online-business-jN-aR6qdYuo-NDa6-ySp9kw.1400x1400.jpg",
            "title": "The Smart Passive Income Online Business and Blogging Podcast",
            "country": "United States",
            "website": "https://art19.com/shows/smart-passive-income-podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              97,
              67,
              94,
              111,
              115,
              127,
              98,
              157,
              171,
              144,
              93,
              173
            ],
            "itunes_id": 383084001,
            "publisher": "Pat Flynn",
            "thumbnail": "https://production.listennotes.com/podcasts/the-smart-passive-income-online-business-sF24owQHYWy-NDa6-ySp9kw.300x300.jpg",
            "is_claimed": false,
            "description": "\n      <p>Pat Flynn from The Smart Passive Income Blog reveals all of his online business and blogging strategies, income sources and killer marketing tips and tricks so you can be ahead of the curve with your online business or blog. Discover how you can create multiple passive income streams that work for you so that you can have the time and freedom to do what you love, whether it's traveling the world, or just living comfortably at home. Since 2008, he's been supporting his family with his many online businesses, and he's been openly sharing his wins, his losses, and all the lessons in between with the community of energetic but humble entrepreneurs who follow him. Self-proclaimed \"crash test dummy of online business\", you'll learn about building authority online, email marketing, building a team and outsourcing, content marketing, podcasting, search engine optimization, niche sites, social media strategies, how to get more traffic, creating online courses, affiliate marketing, and productivity tips so that you create something amazing without burning yourself out. It's a mix of interviews, special co-hosts and solo shows from Pat you're not going to want to miss. Hit subscribe, and get ready to change your life.</p><p><br></p>\n    ",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 70,
            "total_episodes": 729,
            "listennotes_url": "https://www.listennotes.com/c/499661f3589f42aaa1532673e0e0aedf/",
            "audio_length_sec": 2471,
            "explicit_content": false,
            "latest_episode_id": "5a7eca894d3d4a33b91a119506b8da9e",
            "latest_pub_date_ms": 1694761200000,
            "earliest_pub_date_ms": 1279551600722,
            "update_frequency_hours": 83,
            "listen_score_global_rank": "0.05%"
          }
        ]
  return (
    <Box height={"75vh"} overflow={"scroll"} p={"12px"}>
        <RecomendationList data={rec}/>
    </Box>
  )
}

export default Recommendations