import React from 'react'
import {Box} from "@chakra-ui/react"
import RecomendationList from './RecomendationList'
import fetcher from '@/app/utils/fetcher'


const Recommendations = async ({params,searchParams}) => {
    
    const rec =  [
          {
            "id": "805535e1de5a4c7991f4f323e82ce9e7",
            "rss": "https://bryankramer.libsyn.com/rss",
            "type": "episodic",
            "email": "bryan.kramer@purematter.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9icnlhbmtyYW1lci5saWJzeW4uY29tL3Jzcw==",
              "spotify_url": "",
              "youtube_url": "",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "bryankramer",
              "facebook_handle": "",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/the-bryan-kramer-show-bryan-kramer-Br0M_IayKc3-0SCl91ZT-bU.1400x1400.jpg",
            "title": "The Bryan Kramer Show",
            "country": "United States",
            "website": "http://bryankramer.libsyn.com/podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              67,
              88,
              90,
              93,
              97
            ],
            "itunes_id": 1078655111,
            "publisher": "Bryan Kramer",
            "thumbnail": "https://production.listennotes.com/podcasts/the-bryan-kramer-show-bryan-kramer-E7o80typv_b-0SCl91ZT-bU.300x300.jpg",
            "is_claimed": false,
            "description": "Join us as Bryan Kramer deconstructs human behavior and digs deep to share tactics, tools and tricks you can use every day to help you reach peak performance. In each show, Bryan interviews high-profile guests hitting consistent home runs in business, entrepreneurialism marketing and social. Bryan is a TED speaker, USA Today best-selling author, and CEO who consults Fortune 500 clients such as IBM, Cisco, NFL, Harvard University and NASA. He's known for his books Human to Human, #H2H and Shareology. Forbes calls him a \"Zen master to digital marketers.\"",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 35,
            "total_episodes": 64,
            "listennotes_url": "https://www.listennotes.com/c/805535e1de5a4c7991f4f323e82ce9e7/",
            "audio_length_sec": 1695,
            "explicit_content": false,
            "latest_episode_id": "99eb35864e2242a480f4709ded9471b5",
            "latest_pub_date_ms": 1502287200000,
            "earliest_pub_date_ms": 1453246535000,
            "update_frequency_hours": 327,
            "listen_score_global_rank": "3%"
          },
          {
            "id": "7060b5d48b3440ba9668f9af2a90fa7f",
            "rss": "https://www.spreaker.com/show/4920844/episodes/feed",
            "type": "episodic",
            "email": null,
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy80ZjJjNjZmMC9wb2RjYXN0L3Jzcw==",
              "spotify_url": "https://open.spotify.com/show/62soqGPhnYJBRrP2vSAk6b",
              "youtube_url": "",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "",
              "facebook_handle": "",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/the-tim-ferriss-show-5-minute-podcast-mpqMa73u08D-mYx8LcSkhz1.1400x1400.jpg",
            "title": "The Tim Ferriss Show | 5 minute podcast summaries",
            "country": "United States",
            "website": "https://www.spreaker.com/show/the-tim-ferriss-show-5-minute-podcast-su?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              111,
              181,
              67
            ],
            "itunes_id": 1556286643,
            "publisher": "5 minute podcast summaries",
            "thumbnail": "https://production.listennotes.com/podcasts/the-tim-ferriss-show-5-minute-podcast-XMuN8q2Jorb-mYx8LcSkhz1.300x300.jpg",
            "is_claimed": false,
            "description": "5 minute summaries of The Tim Ferriss Show's podcast episodes. Get the best insights and ideas in much less time, more at owltail.com<br /><br />Written summaries: <a href=\"https://www.owltail.com/summaries/75553-the-tim-ferriss-show\" rel=\"noopener\">https://www.owltail.com/summaries/75553-the-tim-ferriss-show</a><br /><br />Other podcast summaries in Apple Podcasts: <a href=\"http://bit.ly/5-min-summaries\" rel=\"noopener\">http://bit.ly/5-min-summaries</a><br /><br />Other podcast summaries In other apps, search 'podcast summaries'.<br /><br />Tim Ferriss is a self-experimenter and bestselling author, best known for The 4-Hour Workweek, which has been translated into 40+ languages. Newsweek calls him \"the world's best human guinea pig,\" and The New York Times calls him \"a cross between Jack Welch and a Buddhist monk.\" In this show, he deconstructs world-class performers from eclectic areas (investing, chess, pro sports, etc.), digging deep to find the tools, tactics, and tricks that listeners can use.",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 35,
            "total_episodes": 12,
            "listennotes_url": "https://www.listennotes.com/c/7060b5d48b3440ba9668f9af2a90fa7f/",
            "audio_length_sec": 221,
            "explicit_content": false,
            "latest_episode_id": "9163fe8fdfc34710af8d41b575023e07",
            "latest_pub_date_ms": 1625881044000,
            "earliest_pub_date_ms": 1619229600011,
            "update_frequency_hours": 165,
            "listen_score_global_rank": "3%"
          },
          {
            "id": "d1344e580523433e9e7b6d3d17579c68",
            "rss": "https://feeds.acast.com/public/shows/eddbcc04-6cf8-4a7b-8bf7-f29cb306da8c",
            "type": "episodic",
            "email": null,
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5hY2FzdC5jb20vcHVibGljL3Nob3dzL2VkZGJjYzA0LTZjZjgtNGE3Yi04YmY3LWYyOWNiMzA2ZGE4Yw==",
              "spotify_url": "",
              "youtube_url": "",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "",
              "facebook_handle": "",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/the-guinea-pig-the-guinea-pig-podcast-f71pCJnAd8Q-bpDvSg1QWR4.1400x1400.jpg",
            "title": "The Guinea Pig",
            "country": "United States",
            "website": null,
            "language": "English",
            "genre_ids": [
              90,
              107,
              111,
              67
            ],
            "itunes_id": 1453993716,
            "publisher": "The Guinea Pig Podcast",
            "thumbnail": "https://production.listennotes.com/podcasts/the-guinea-pig-the-guinea-pig-podcast-eQwm9xXzlPv-bpDvSg1QWR4.300x300.jpg",
            "is_claimed": false,
            "description": "Leading surgeon and founder of cult brand MZ SKIN, Dr Maryam Zamani and ex-Vogue editor-at-Large, Fiona Golfar present The Guinea Pig podcast!Fiona and Maryam share their honest opinions and hilarious real-life experiences and give essential safety advice to those considering any kind of aesthetic procedure.For adults only, this bi-weekly podcast covers the latest aesthetic treatment reviews by the resident guinea pig, Fiona Golfar, supported by necessary medical advice and insights from Dr Maryam Zamani.Fiona tries the treatments - so you don’t have to - allowing the listener to decide for themselves once they are armed with the necessary knowledge, questions to ask and potential risks. Maryam and Fiona chat openly and candidly about products and procedures aided by experts & high-profile friends to offer advice and insights to anyone considering a treatment.So if you, or someone you know is thinking of changing their moisturiser, dealing with tired looking eyes, or even having a neck-lift, The Guinea Pig is here to help you!<br /><hr><p style='color:grey; font-size:0.75em;'> Hosted on Acast. See <a style='color:grey;' target='_blank' rel='noopener noreferrer' href='https://acast.com/privacy'>acast.com/privacy</a> for more information.</p>",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 40,
            "total_episodes": 70,
            "listennotes_url": "https://www.listennotes.com/c/d1344e580523433e9e7b6d3d17579c68/",
            "audio_length_sec": 1715,
            "explicit_content": true,
            "latest_episode_id": "7ce4a41ab7034fb2936646236b392dc0",
            "latest_pub_date_ms": 1613008800000,
            "earliest_pub_date_ms": 1550841504069,
            "update_frequency_hours": 319,
            "listen_score_global_rank": "1.5%"
          },
          {
            "id": "f9d5885d7cf7485d891e82dea3186640",
            "rss": "https://rss.art19.com/how-i-built-this",
            "type": "episodic",
            "email": "iwonder@wondery.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9yc3MuYXJ0MTkuY29tL2hvdy1pLWJ1aWx0LXRoaXM=",
              "spotify_url": "https://open.spotify.com/show/6E709HRH7XaiZrMfgtNCun",
              "youtube_url": "",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "HowIBuiltThis",
              "facebook_handle": "howibuiltthis",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/how-i-built-this-with-guy-raz-guy-raz-wondery-I8nbimW4uEZ-UC0qH23iP9T.1400x1400.jpg",
            "title": "How I Built This with Guy Raz",
            "country": "United States",
            "website": "https://wondery.com/shows/how-i-built-this/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              157,
              90,
              173,
              94,
              106,
              127,
              93,
              67,
              171
            ],
            "itunes_id": 1150510297,
            "publisher": "Guy Raz | Wondery",
            "thumbnail": "https://production.listennotes.com/podcasts/how-i-built-this-with-guy-raz-guy-raz-wondery-6hPxKdwGUe0-UC0qH23iP9T.300x300.jpg",
            "is_claimed": false,
            "description": "\n      <p>Guy Raz interviews the world’s best-known entrepreneurs to learn how they built their iconic brands. In each episode, founders reveal deep, intimate moments of doubt and failure, and share insights on their eventual success. <em>How I Built This </em>is a master-class on innovation, creativity, leadership and how to navigate challenges of all kinds.</p><p>New episodes on Mondays and Thursdays for free. Listen 1-week early and to all episodes ad-free with Wondery+ or Amazon Music with a Prime membership or Amazon Music Unlimited subscription.</p><p>Get your How I Built This merch at <a href=\"https://wonderyshop.com/pages/howibuiltthis ?utm_source=hibt-podcast&utm_medium=referral&utm_campaign=hibt-description\" rel=\"noopener noreferrer\" target=\"_blank\">WonderyShop.com/HowIBuiltThis</a></p><p><br></p>\n    ",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 83,
            "total_episodes": 557,
            "listennotes_url": "https://www.listennotes.com/c/f9d5885d7cf7485d891e82dea3186640/",
            "audio_length_sec": 2989,
            "explicit_content": false,
            "latest_episode_id": "ab7c87a151b94305bd6805882b1185e9",
            "latest_pub_date_ms": 1694664600000,
            "earliest_pub_date_ms": 1472828160550,
            "update_frequency_hours": 78,
            "listen_score_global_rank": "0.01%"
          },
          {
            "id": "fe6864628066420c8103c94e91e72eb3",
            "rss": "https://anchor.fm/s/f39a864/podcast/rss",
            "type": "episodic",
            "email": "justin.schnell@vaynermedia.com",
            "extra": {
              "url1": "https://medium.com/@garyvee",
              "url2": "https://www.snapchat.com/add/garyvee",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cDovL2Fza2dhcnl2ZWUuZ2FyeXZlZS5saWJzeW5wcm8uY29tL3Jzcw==",
              "spotify_url": "https://open.spotify.com/show/6SZVsPIxPfVs6aavqM1peY",
              "youtube_url": "https://www.youtube.com/user/garyvaynerchuk",
              "linkedin_url": "https://www.linkedin.com/in/garyvaynerchuk/",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "garyvee",
              "facebook_handle": "gary",
              "amazon_music_url": "https://music.amazon.com/podcasts/97113abf-5c18-4c7e-8d2b-efcf161f4848/the-garyvee-audio-experience",
              "instagram_handle": "garyvee"
            },
            "image": "https://production.listennotes.com/podcasts/the-garyvee-audio-experience-gary-vaynerchuk-gNfBoYH9uUy-X0Dfm7O_o3y.1400x1400.jpg",
            "title": "The GaryVee Audio Experience",
            "country": "United States",
            "website": "http://www.garyvaynerchuk.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              95,
              127,
              169,
              78,
              157,
              97,
              98,
              173,
              93,
              67,
              171
            ],
            "itunes_id": 928159684,
            "publisher": "Gary Vaynerchuk",
            "thumbnail": "https://production.listennotes.com/podcasts/the-garyvee-audio-experience-gary-vaynerchuk-U9oAGIlVtq6-X0Dfm7O_o3y.300x300.jpg",
            "is_claimed": false,
            "description": "Welcome to The GaryVee Audio Experience, hosted by entrepreneur, CEO, investor, content creator, and public speaker Gary Vaynerchuk. On this podcast you'll find a mix of the #AskGaryVee show episodes, keynote speeches on marketing and business, segments from my DAILYVEE video series, interviews and fireside chats I've given, as well as new and current thoughts I record originally for this audio experience!\n\n",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 80,
            "total_episodes": 2732,
            "listennotes_url": "https://www.listennotes.com/c/fe6864628066420c8103c94e91e72eb3/",
            "audio_length_sec": 1864,
            "explicit_content": true,
            "latest_episode_id": "4a26253059ed4e42a67c02c6d55fe487",
            "latest_pub_date_ms": 1694761200000,
            "earliest_pub_date_ms": 1412179202542,
            "update_frequency_hours": 24,
            "listen_score_global_rank": "0.01%"
          },
          {
            "id": "9f6ee51adfb046cc9936490abd2666ce",
            "rss": "https://feeds.simplecast.com/AAvup9Zz",
            "type": "episodic",
            "email": "podcast@schoolofgreatness.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9BQXZ1cDlaeg==",
              "spotify_url": "https://open.spotify.com/show/07GQhOZboEZOE1ysnFLipT",
              "youtube_url": "https://www.youtube.com/user/lewishowes",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "lewishowes",
              "facebook_handle": "lewishowes",
              "amazon_music_url": "",
              "instagram_handle": ""
            },
            "image": "https://production.listennotes.com/podcasts/the-school-of-greatness-lewis-howes-Ggb9PDwVr63-H1zdqljixbp.1400x1400.jpg",
            "title": "The School of Greatness",
            "country": "United States",
            "website": "https://www.stitcher.com?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              77,
              78,
              90,
              89,
              97,
              94,
              171,
              93,
              181,
              111,
              91,
              67,
              88
            ],
            "itunes_id": 596047499,
            "publisher": "Lewis Howes",
            "thumbnail": "https://production.listennotes.com/podcasts/the-school-of-greatness-lewis-howes-jyfMSXd41U8-H1zdqljixbp.300x300.jpg",
            "is_claimed": false,
            "description": "Lewis Howes is a New York Times best-selling author, 2x All-American athlete, keynote speaker, and entrepreneur. The School of Greatness shares inspiring interviews from the most successful people on the planet—world-renowned leaders in business, entertainment, sports, science, health, and literature—to inspire YOU to unlock your inner greatness and live your best life.",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 78,
            "total_episodes": 1507,
            "listennotes_url": "https://www.listennotes.com/c/9f6ee51adfb046cc9936490abd2666ce/",
            "audio_length_sec": 3155,
            "explicit_content": false,
            "latest_episode_id": "176c41a458714823abfc008d1b49c877",
            "latest_pub_date_ms": 1694761200000,
            "earliest_pub_date_ms": 1358928001491,
            "update_frequency_hours": 45,
            "listen_score_global_rank": "0.01%"
          },
          {
            "id": "a409b8bb93f44054a7be2d6b30843899",
            "rss": "https://entrepreneuronfire.libsyn.com/rss",
            "type": "episodic",
            "email": "John@EntrepreneurOnFire.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9lbnRyZXByZW5ldXJvbmZpcmUubGlic3luLmNvbS9yc3M=",
              "spotify_url": "https://open.spotify.com/show/25wgHxrQY2e7WNeV4UtECI",
              "youtube_url": "https://www.youtube.com/channel/UCXfzpliAfdjParawJljHo2g",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "johnleedumas",
              "facebook_handle": "johnleedumas1",
              "amazon_music_url": "https://music.amazon.com/podcasts/4728a7fc-731f-4b18-971b-85b0b8c2e784/entrepreneurs-on-fire",
              "instagram_handle": "johnleedumas"
            },
            "image": "https://production.listennotes.com/podcasts/entrepreneurs-on-fire-john-lee-dumas-of-DekxRsp0tNA-1WOhT7u6VQb.1400x1400.jpg",
            "title": "Entrepreneurs on Fire",
            "country": "United States",
            "website": "https://www.eofire.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              88,
              111,
              90,
              94,
              97,
              169,
              157,
              173,
              93,
              67,
              171
            ],
            "itunes_id": 564001633,
            "publisher": "John Lee Dumas of EOFire",
            "thumbnail": "https://production.listennotes.com/podcasts/entrepreneurs-on-fire-john-lee-dumas-of-o7xODP0r6-Q-1WOhT7u6VQb.300x300.jpg",
            "is_claimed": true,
            "description": "John Lee Dumas is the founder and host of the award winning podcast, Entrepreneurs On Fire. With over 100 million listens of his 3000+ episodes, JLD has turned Entrepreneurs On Fire into a media empire that generates over a million listens every month and 7-figures of NET annual revenue 8-years in a row. His first traditionally published book, The Common Path to Uncommon Success is the modern day version of Think and Grow Rich with a revolutionary 17-step roadmap to financial freedom and fulfillment. Learn more at UncommonSuccessBook.com",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 69,
            "total_episodes": 3473,
            "listennotes_url": "https://www.listennotes.com/c/a409b8bb93f44054a7be2d6b30843899/",
            "audio_length_sec": 1804,
            "explicit_content": false,
            "latest_episode_id": "de2a4259999646abb0f64f2898ad84b1",
            "latest_pub_date_ms": 1694766600000,
            "earliest_pub_date_ms": 1348297203456,
            "update_frequency_hours": 24,
            "listen_score_global_rank": "0.05%"
          },
          {
            "id": "499661f3589f42aaa1532673e0e0aedf",
            "rss": "https://rss.art19.com/smart-passive-income-podcast",
            "type": "episodic",
            "email": "podcasts@teamspi.com",
            "extra": {
              "url1": "",
              "url2": "",
              "url3": "",
              "google_url": "https://podcasts.google.com/feed/aHR0cHM6Ly9yc3MuYXJ0MTkuY29tL3NtYXJ0LXBhc3NpdmUtaW5jb21lLXBvZGNhc3Q=",
              "spotify_url": "https://open.spotify.com/show/7wjv5MRCXWXImqTFhcufLy",
              "youtube_url": "https://www.youtube.com/user/smartpassiveincome",
              "linkedin_url": "",
              "wechat_handle": "",
              "patreon_handle": "",
              "twitter_handle": "patflynn",
              "facebook_handle": "smartpassiveincome",
              "amazon_music_url": "https://music.amazon.com/podcasts/341282a1-cba9-4188-aa58-e09a51ccaa87/the-smart-passive-income-online-business-and-blogging-podcast",
              "instagram_handle": "patflynn"
            },
            "image": "https://production.listennotes.com/podcasts/the-smart-passive-income-online-business-jN-aR6qdYuo-NDa6-ySp9kw.1400x1400.jpg",
            "title": "The Smart Passive Income Online Business and Blogging Podcast",
            "country": "United States",
            "website": "https://art19.com/shows/smart-passive-income-podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
            "language": "English",
            "genre_ids": [
              97,
              67,
              94,
              111,
              115,
              127,
              98,
              157,
              171,
              144,
              93,
              173
            ],
            "itunes_id": 383084001,
            "publisher": "Pat Flynn",
            "thumbnail": "https://production.listennotes.com/podcasts/the-smart-passive-income-online-business-sF24owQHYWy-NDa6-ySp9kw.300x300.jpg",
            "is_claimed": false,
            "description": "\n      <p>Pat Flynn from The Smart Passive Income Blog reveals all of his online business and blogging strategies, income sources and killer marketing tips and tricks so you can be ahead of the curve with your online business or blog. Discover how you can create multiple passive income streams that work for you so that you can have the time and freedom to do what you love, whether it's traveling the world, or just living comfortably at home. Since 2008, he's been supporting his family with his many online businesses, and he's been openly sharing his wins, his losses, and all the lessons in between with the community of energetic but humble entrepreneurs who follow him. Self-proclaimed \"crash test dummy of online business\", you'll learn about building authority online, email marketing, building a team and outsourcing, content marketing, podcasting, search engine optimization, niche sites, social media strategies, how to get more traffic, creating online courses, affiliate marketing, and productivity tips so that you create something amazing without burning yourself out. It's a mix of interviews, special co-hosts and solo shows from Pat you're not going to want to miss. Hit subscribe, and get ready to change your life.</p><p><br></p>\n    ",
            "looking_for": {
              "guests": false,
              "cohosts": false,
              "sponsors": false,
              "cross_promotion": false
            },
            "listen_score": 70,
            "total_episodes": 729,
            "listennotes_url": "https://www.listennotes.com/c/499661f3589f42aaa1532673e0e0aedf/",
            "audio_length_sec": 2471,
            "explicit_content": false,
            "latest_episode_id": "5a7eca894d3d4a33b91a119506b8da9e",
            "latest_pub_date_ms": 1694761200000,
            "earliest_pub_date_ms": 1279551600722,
            "update_frequency_hours": 83,
            "listen_score_global_rank": "0.05%"
          }
        ]
    const epRec = [
      {
        "id": "05534e9d98a1469c8e402b7103d77015",
        "link": "https://www.coindesk.com/podcasts/markets-daily?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
        "audio": "https://www.listennotes.com/e/p/05534e9d98a1469c8e402b7103d77015/",
        "image": "https://production.listennotes.com/podcasts/markets-daily-crypto-roundup-coindesk-xEObzQi6qJr-VTiDtLAInyo.1400x1400.jpg",
        "title": "Most Influential 2021: Roham Gharegozlou (Pt. 1)",
        "podcast": {
          "id": "6c7ed315628b441c8a1bf0e331da2ba9",
          "image": "https://production.listennotes.com/podcasts/markets-daily-crypto-roundup-coindesk-xEObzQi6qJr-VTiDtLAInyo.1400x1400.jpg",
          "title": "Markets Daily Crypto Roundup",
          "publisher": "CoinDesk",
          "thumbnail": "https://production.listennotes.com/podcasts/markets-daily-crypto-roundup-coindesk-q7QR_ynu6Hv-VTiDtLAInyo.300x300.jpg",
          "listen_score": 43,
          "listennotes_url": "https://www.listennotes.com/c/6c7ed315628b441c8a1bf0e331da2ba9/",
          "listen_score_global_rank": "1%"
        },
        "thumbnail": "https://production.listennotes.com/podcasts/markets-daily-crypto-roundup-coindesk-q7QR_ynu6Hv-VTiDtLAInyo.300x300.jpg",
        "description": "<p>On today's show CoinDesk Columnist and author of 7 books, Jeff Wilser, picks Roham Gharegozlou as one of CoinDesk's Most Influential in 2021. The man behind CryptoKitties and NBA Top Shot has big plans for digital sports and the open metaverse. (Part 1)</p><p><a href=\"https://www.coindesk.com/business/2021/12/07/most-influential-2021-roham-gharegozlou/\" rel=\"noopener noreferrer\" target=\"_blank\">Read the story here.</a></p><p><br /></p><p><em>This episode is sponsored by </em><a href=\"https://www.kava.io/marketsdaily?utm_campaign=Ad%20Affiliates&utm_source=markets_daily&utm_medium=banner_ad&utm_term=home\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Kava</em></a>, <a href=\"https://nexo.io/?%20utm_source=coindesk&utm_medium=fixed&utm_campaign=coindesk_sponsoredline_%20nov21\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Nexo.io</em></a><em> and </em><a href=\"https://markets.chainalysis.com/?utm_source=coindesk&utm_medium=podcast\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Market Intel by Chainalysis</em></a><em>.</em></p><p><br /></p><p><em>This episode was edited & produced by </em><a href=\"https://www.coindesk.com/author/adrian-blust\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Adrian Blust</em></a><em>. </em></p><p><em>-</em></p><p><a href=\"https://www.kava.io/marketsdaily?utm_campaign=Ad%20Affiliates&utm_source=markets_daily&utm_medium=banner_ad&utm_term=home\" rel=\"noopener noreferrer\" target=\"_blank\"><strong><em>Kava</em></strong></a><em> lets you mint stablecoins, lend, borrow, earn and swap safely across the world’s biggest crypto assets. Connect to the world's largest cryptocurrencies, ecosystems and financial applications on DeFi’s most trusted, scalable and secure earning platform with </em><a href=\"https://www.kava.io/marketsdaily?utm_campaign=Ad%20Affiliates&utm_source=markets_daily&utm_medium=banner_ad&utm_term=home\" rel=\"noopener noreferrer\" target=\"_blank\"><em>kava.io</em></a><em>.</em></p><p><em>-</em></p><p><a href=\"https://nexo.io/?%20utm_source=coindesk&utm_medium=fixed&utm_campaign=coindesk_sponsoredline_%20nov21\" rel=\"noopener noreferrer\" target=\"_blank\"><strong><em>Nexo</em></strong></a><em> is a powerful, all-in-one crypto platform where you can securely store your assets. Invest, borrow, exchange and earn up to 12% APR on Bitcoin and 20+ other top coins. Insured for $375M and audited in real-time by Armanino, Nexo is rated excellent on Trustpilot. Get started today at </em><a href=\"https://nexo.io/?%20utm_source=coindesk&utm_medium=fixed&utm_campaign=coindesk_sponsoredline_%20nov21\" rel=\"noopener noreferrer\" target=\"_blank\"><em>nexo.io</em></a><em>.</em></p><p><em>-</em></p><p><a href=\"https://markets.chainalysis.com/?utm_source=coindesk&utm_medium=podcast\" rel=\"noopener noreferrer\" target=\"_blank\"><strong><em>Market Intel by Chainalysis</em></strong></a><em>—the Blockchain Data Platform—arms your team with the most complete on-chain dataset to make informed crypto investments, deliver original research, and identify and confidently fund emerging players in the market. See Chainalysis </em><a href=\"https://markets.chainalysis.com/?utm_source=coindesk&utm_medium=podcast\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Market Intel in action now</em></a><em>.</em></p><p>See Privacy Policy at <a href=\"https://art19.com/privacy\" rel=\"noopener noreferrer\" target=\"_blank\">https://art19.com/privacy</a> and California Privacy Notice at <a href=\"https://art19.com/privacy#do-not-sell-my-info\" rel=\"noopener noreferrer\" target=\"_blank\">https://art19.com/privacy#do-not-sell-my-info</a>.</p>",
        "pub_date_ms": 1640430000558,
        "guid_from_rss": "gid://art19-episode-locator/V0/qTL8NjCdWoTCfTWkK6E-ErwcwkPWKVNIhOlwHZH7Cbg",
        "listennotes_url": "https://www.listennotes.com/e/05534e9d98a1469c8e402b7103d77015/",
        "audio_length_sec": 574,
        "explicit_content": false,
        "maybe_audio_invalid": false,
        "listennotes_edit_url": "https://www.listennotes.com/e/05534e9d98a1469c8e402b7103d77015/#edit"
      },
      {
        "id": "3a2016291aaa415abb9563bf8192ade7",
        "link": "https://foundersproject.inc.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
        "audio": "https://www.listennotes.com/e/p/3a2016291aaa415abb9563bf8192ade7/",
        "image": "https://production.listennotes.com/podcasts/inc-founders-project-with-alexa-von-tobel-kmUz9vWdufn-M25bgqtK8-I.1400x1400.jpg",
        "title": "How to Build Community Through Ownership with Roham Gharegozlou of Dapper Labs",
        "podcast": {
          "id": "0694a18b25354ce593c3aeba7fb94d67",
          "image": "https://production.listennotes.com/podcasts/inc-founders-project-with-alexa-von-tobel-kmUz9vWdufn-M25bgqtK8-I.1400x1400.jpg",
          "title": "Inc. Founders Project with Alexa von Tobel ",
          "publisher": "Inc. Magazine",
          "thumbnail": "https://production.listennotes.com/podcasts/inc-founders-project-with-alexa-von-tobel-2jsPht5pNkI-M25bgqtK8-I.300x300.jpg",
          "listen_score": 38,
          "listennotes_url": "https://www.listennotes.com/c/0694a18b25354ce593c3aeba7fb94d67/",
          "listen_score_global_rank": "2%"
        },
        "thumbnail": "https://production.listennotes.com/podcasts/inc-founders-project-with-alexa-von-tobel-2jsPht5pNkI-M25bgqtK8-I.300x300.jpg",
        "description": "<p>If you've heard of NFTs (non-fungible tokens), it's likely thanks to the work of Roham Gharegozlou. Roham is the Co-Founder and CEO of Dapper Labs, the NFT company that has created some of the most viral brands out there, from CryptoKitties to NBA Top Shot. Through his venture studio Axiom Zen, he started looking into crypto back in 2014. With a mission to bring play to crypto, Dapper Labs has been named one of the most innovative gaming companies by Fast Company and has created some of the most broadly used applications in the history of crypto. Roham shares how NBA Top Shot scaled to over one million users, why he thinks of NFTs as the next evolution of social media, and why entrepreneurship requires a healthy balance of optimism and paranoia. </p>",
        "pub_date_ms": 1646215200067,
        "guid_from_rss": "09eb05a6-996e-11ec-9f17-ef743a58b593",
        "listennotes_url": "https://www.listennotes.com/e/3a2016291aaa415abb9563bf8192ade7/",
        "audio_length_sec": 1792,
        "explicit_content": false,
        "maybe_audio_invalid": false,
        "listennotes_edit_url": "https://www.listennotes.com/e/3a2016291aaa415abb9563bf8192ade7/#edit"
      },
      {
        "id": "221ff88340b941148ad90749f0c745e7",
        "link": "https://foundersproject.inc.com/?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
        "audio": "https://www.listennotes.com/e/p/221ff88340b941148ad90749f0c745e7/",
        "image": "https://production.listennotes.com/podcasts/inc-founders-project-with-alexa-von-tobel-kmUz9vWdufn-M25bgqtK8-I.1400x1400.jpg",
        "title": "Flashback Episode: How to Build Community Through Ownership with Roham Gharegozlou of Dapper Labs",
        "podcast": {
          "id": "0694a18b25354ce593c3aeba7fb94d67",
          "image": "https://production.listennotes.com/podcasts/inc-founders-project-with-alexa-von-tobel-kmUz9vWdufn-M25bgqtK8-I.1400x1400.jpg",
          "title": "Inc. Founders Project with Alexa von Tobel ",
          "publisher": "Inc. Magazine",
          "thumbnail": "https://production.listennotes.com/podcasts/inc-founders-project-with-alexa-von-tobel-2jsPht5pNkI-M25bgqtK8-I.300x300.jpg",
          "listen_score": 38,
          "listennotes_url": "https://www.listennotes.com/c/0694a18b25354ce593c3aeba7fb94d67/",
          "listen_score_global_rank": "2%"
        },
        "thumbnail": "https://production.listennotes.com/podcasts/inc-founders-project-with-alexa-von-tobel-2jsPht5pNkI-M25bgqtK8-I.300x300.jpg",
        "description": "<p>If you've heard of NFTs (non-fungible tokens), it's likely thanks to the work of Roham Gharegozlou. Roham is the Co-Founder and CEO of Dapper Labs, the NFT company that has created some of the most viral brands out there, from CryptoKitties to NBA Top Shot. Through his venture studio Axiom Zen, he started looking into crypto back in 2014. With a mission to bring play to crypto, Dapper Labs has been named one of the most innovative gaming companies by Fast Company and has created some of the most broadly used applications in the history of crypto. Roham shares how NBA Top Shot scaled to over one million users, why he thinks of NFTs as the next evolution of social media, and why entrepreneurship requires a healthy balance of optimism and paranoia. </p>",
        "pub_date_ms": 1655888400051,
        "guid_from_rss": "ff7cc4d0-f172-11ec-b560-e703d370d4d3",
        "listennotes_url": "https://www.listennotes.com/e/221ff88340b941148ad90749f0c745e7/",
        "audio_length_sec": 1792,
        "explicit_content": false,
        "maybe_audio_invalid": false,
        "listennotes_edit_url": "https://www.listennotes.com/e/221ff88340b941148ad90749f0c745e7/#edit"
      },
      {
        "id": "774e65cead6e4b548f09a1a7bf7c55af",
        "link": "https://www.coindesk.com/podcasts/markets-daily?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
        "audio": "https://www.listennotes.com/e/p/774e65cead6e4b548f09a1a7bf7c55af/",
        "image": "https://production.listennotes.com/podcasts/markets-daily-crypto-roundup-coindesk-xEObzQi6qJr-VTiDtLAInyo.1400x1400.jpg",
        "title": "Most Influential 2021: Roham Gharegozlou (Pt. 2)",
        "podcast": {
          "id": "6c7ed315628b441c8a1bf0e331da2ba9",
          "image": "https://production.listennotes.com/podcasts/markets-daily-crypto-roundup-coindesk-xEObzQi6qJr-VTiDtLAInyo.1400x1400.jpg",
          "title": "Markets Daily Crypto Roundup",
          "publisher": "CoinDesk",
          "thumbnail": "https://production.listennotes.com/podcasts/markets-daily-crypto-roundup-coindesk-q7QR_ynu6Hv-VTiDtLAInyo.300x300.jpg",
          "listen_score": 43,
          "listennotes_url": "https://www.listennotes.com/c/6c7ed315628b441c8a1bf0e331da2ba9/",
          "listen_score_global_rank": "1%"
        },
        "thumbnail": "https://production.listennotes.com/podcasts/markets-daily-crypto-roundup-coindesk-q7QR_ynu6Hv-VTiDtLAInyo.300x300.jpg",
        "description": "<p>On today's show CoinDesk Columnist and author of 7 books, Jeff Wilser, picks Roham Gharegozlou as one of CoinDesk's Most Influential in 2021. The man behind CryptoKitties and NBA Top Shot has big plans for digital sports and the open metaverse. (Part 2)</p><p><a href=\"https://www.coindesk.com/business/2021/12/07/most-influential-2021-roham-gharegozlou/\" rel=\"noopener noreferrer\" target=\"_blank\">Read the story here.</a></p><p><br /></p><p><em>This episode is sponsored by </em><a href=\"https://www.kava.io/marketsdaily?utm_campaign=Ad%20Affiliates&utm_source=markets_daily&utm_medium=banner_ad&utm_term=home\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Kava</em></a>, <a href=\"https://nexo.io/?%20utm_source=coindesk&utm_medium=fixed&utm_campaign=coindesk_sponsoredline_%20nov21\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Nexo.io</em></a><em> and </em><a href=\"https://markets.chainalysis.com/?utm_source=coindesk&utm_medium=podcast\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Market Intel by Chainalysis</em></a><em>.</em></p><p><br /></p><p><em>This episode was edited & produced by </em><a href=\"https://www.coindesk.com/author/adrian-blust\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Adrian Blust</em></a><em>.  </em></p><p><em>-</em></p><p><a href=\"https://www.kava.io/marketsdaily?utm_campaign=Ad%20Affiliates&utm_source=markets_daily&utm_medium=banner_ad&utm_term=home\" rel=\"noopener noreferrer\" target=\"_blank\"><strong><em>Kava</em></strong></a><em> lets you mint stablecoins, lend, borrow, earn and swap safely across the world’s biggest crypto assets. Connect to the world's largest cryptocurrencies, ecosystems and financial applications on DeFi’s most trusted, scalable and secure earning platform with </em><a href=\"https://www.kava.io/marketsdaily?utm_campaign=Ad%20Affiliates&utm_source=markets_daily&utm_medium=banner_ad&utm_term=home\" rel=\"noopener noreferrer\" target=\"_blank\"><em>kava.io</em></a><em>.</em></p><p><em>-</em></p><p><a href=\"https://nexo.io/?%20utm_source=coindesk&utm_medium=fixed&utm_campaign=coindesk_sponsoredline_%20nov21\" rel=\"noopener noreferrer\" target=\"_blank\"><strong><em>Nexo</em></strong></a><em> is a powerful, all-in-one crypto platform where you can securely store your assets. Invest, borrow, exchange and earn up to 12% APR on Bitcoin and 20+ other top coins. Insured for $375M and audited in real-time by Armanino, Nexo is rated excellent on Trustpilot. Get started today at </em><a href=\"https://nexo.io/?%20utm_source=coindesk&utm_medium=fixed&utm_campaign=coindesk_sponsoredline_%20nov21\" rel=\"noopener noreferrer\" target=\"_blank\"><em>nexo.io</em></a><em>.</em></p><p><em>-</em></p><p><a href=\"https://markets.chainalysis.com/?utm_source=coindesk&utm_medium=podcast\" rel=\"noopener noreferrer\" target=\"_blank\"><strong><em>Market Intel by Chainalysis</em></strong></a><em>—the Blockchain Data Platform—arms your team with the most complete on-chain dataset to make informed crypto investments, deliver original research, and identify and confidently fund emerging players in the market. See Chainalysis </em><a href=\"https://markets.chainalysis.com/?utm_source=coindesk&utm_medium=podcast\" rel=\"noopener noreferrer\" target=\"_blank\"><em>Market Intel in action now</em></a><em>.</em></p><p>See Privacy Policy at <a href=\"https://art19.com/privacy\" rel=\"noopener noreferrer\" target=\"_blank\">https://art19.com/privacy</a> and California Privacy Notice at <a href=\"https://art19.com/privacy#do-not-sell-my-info\" rel=\"noopener noreferrer\" target=\"_blank\">https://art19.com/privacy#do-not-sell-my-info</a>.</p>",
        "pub_date_ms": 1640516400557,
        "guid_from_rss": "gid://art19-episode-locator/V0/r2o71PPmrHUyC-poZTVb_1aRNHd2tBCgIe_UrksQ3Gk",
        "listennotes_url": "https://www.listennotes.com/e/774e65cead6e4b548f09a1a7bf7c55af/",
        "audio_length_sec": 733,
        "explicit_content": false,
        "maybe_audio_invalid": false,
        "listennotes_edit_url": "https://www.listennotes.com/e/774e65cead6e4b548f09a1a7bf7c55af/#edit"
      },
      {
        "id": "2afa18fe81b64fae9a178ea4e6ea1b78",
        "link": "http://samsungnext.com/podcast?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
        "audio": "https://www.listennotes.com/e/p/2afa18fe81b64fae9a178ea4e6ea1b78/",
        "image": "https://production.listennotes.com/podcasts/whats-next-samsung-next-BOU80jWegKh-kG8U3EdxHWo.1400x1400.jpg",
        "title": "Building blockchain collectibles with Dapper Labs founder Roham Gharegozlou",
        "podcast": {
          "id": "0615f79f64de4f1989d4ad1bac7cbc9e",
          "image": "https://production.listennotes.com/podcasts/whats-next-samsung-next-BOU80jWegKh-kG8U3EdxHWo.1400x1400.jpg",
          "title": "What's NEXT",
          "publisher": "Samsung NEXT",
          "thumbnail": "https://production.listennotes.com/podcasts/whats-next-samsung-next-RaNEz68Vhc0-kG8U3EdxHWo.300x300.jpg",
          "listen_score": 26,
          "listennotes_url": "https://www.listennotes.com/c/0615f79f64de4f1989d4ad1bac7cbc9e/",
          "listen_score_global_rank": "10%"
        },
        "thumbnail": "https://production.listennotes.com/podcasts/whats-next-samsung-next-RaNEz68Vhc0-kG8U3EdxHWo.300x300.jpg",
        "description": "<p>Welcome back to What’s NEXT, the podcast exploring the technology of the future. This is the last in our series of conversations from the Web Summit conference last year. <br> <br>In this episode, Samsung NEXT’s Haley Lancaster speaks with Roham Gharegozlou, the founder and CEO of Dapper Labs, which made CryptoKitties and a number of other decentralized apps. Roham speaks about the early success of CryptoKitties, how his company works with partners like the NBA and Ubisoft, and why Dapper Labs is building a new, developer-friendly blockchain platform called Flow. <br><br></p>",
        "pub_date_ms": 1580972400005,
        "guid_from_rss": "8efdfab2-46e8-11ea-9483-0e1facdaf5fd",
        "listennotes_url": "https://www.listennotes.com/e/2afa18fe81b64fae9a178ea4e6ea1b78/",
        "audio_length_sec": 851,
        "explicit_content": false,
        "maybe_audio_invalid": false,
        "listennotes_edit_url": "https://www.listennotes.com/e/2afa18fe81b64fae9a178ea4e6ea1b78/#edit"
      },
      {
        "id": "3663e1ba8f944df7956378ab332bf12b",
        "link": "https://www.gimletmedia.com/startup?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
        "audio": "https://www.listennotes.com/e/p/3663e1ba8f944df7956378ab332bf12b/",
        "image": "https://production.listennotes.com/podcasts/startup-podcast-gimlet-14zU0c_MOmv-n9PpCBTQvoJ.1400x1400.jpg",
        "title": "Introducing How to Save a Planet",
        "podcast": {
          "id": "0d362b13399240de97602ef614acdcbc",
          "image": "https://production.listennotes.com/podcasts/startup-podcast-gimlet-14zU0c_MOmv-n9PpCBTQvoJ.1400x1400.jpg",
          "title": "StartUp Podcast",
          "publisher": "Gimlet",
          "thumbnail": "https://production.listennotes.com/podcasts/startup-podcast-gimlet-8If7QBKU5jb-n9PpCBTQvoJ.300x300.jpg",
          "listen_score": 73,
          "listennotes_url": "https://www.listennotes.com/c/0d362b13399240de97602ef614acdcbc/",
          "listen_score_global_rank": "0.05%"
        },
        "thumbnail": "https://production.listennotes.com/podcasts/startup-podcast-gimlet-8If7QBKU5jb-n9PpCBTQvoJ.300x300.jpg",
        "description": "<p>Does climate change freak you out? Want to know what we, collectively, can do about it? Us too. How to Save a Planet is a podcast that asks the big questions: what do we need to do to solve the climate crisis, and how do we get it done? </p><p>Join us, journalist Alex Blumberg and scientist and policy nerd Dr. Ayana Elizabeth Johnson, as we scour the Earth for solutions, talk to people who are making a difference, ask hard questions, crack dumb jokes and — episode by episode — figure out how to build the future we want.</p>",
        "pub_date_ms": 1598004000000,
        "guid_from_rss": "25666464-e19c-11ea-bb5d-b3b5dc0bbdef",
        "listennotes_url": "https://www.listennotes.com/e/3663e1ba8f944df7956378ab332bf12b/",
        "audio_length_sec": 714,
        "explicit_content": false,
        "maybe_audio_invalid": false,
        "listennotes_edit_url": "https://www.listennotes.com/e/3663e1ba8f944df7956378ab332bf12b/#edit"
      },
      {
        "id": "b03b9f59a5df4d31bf44e1828353c8e6",
        "link": "https://www.softwaredefinedinterviews.com/ma4?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
        "audio": "https://www.listennotes.com/e/p/b03b9f59a5df4d31bf44e1828353c8e6/",
        "image": "https://production.listennotes.com/podcasts/software-defined-interviews-software-yFixmv_8KZq-y7KRi_flj8t.1400x1400.jpg",
        "title": "Misaligned Incentives Episode 4: You get what you pay for - compensating tech staff is often done poorly",
        "podcast": {
          "id": "13350cb77ad548bc8991dac9657f45b7",
          "image": "https://production.listennotes.com/podcasts/software-defined-interviews-software-yFixmv_8KZq-y7KRi_flj8t.1400x1400.jpg",
          "title": "Software Defined Interviews",
          "publisher": "Software Defined Talk",
          "thumbnail": "https://production.listennotes.com/podcasts/software-defined-interviews-software-N8fPcvt0JmU-y7KRi_flj8t.300x300.jpg",
          "listen_score": null,
          "listennotes_url": "https://www.listennotes.com/c/13350cb77ad548bc8991dac9657f45b7/",
          "listen_score_global_rank": null
        },
        "thumbnail": "https://production.listennotes.com/podcasts/software-defined-interviews-software-N8fPcvt0JmU-y7KRi_flj8t.300x300.jpg",
        "description": "<pre><code>    <p>We discuss compensation, particularly how people in the IT department (&quot;developers,&quot; etc.) are so disconnected from the actual business that compensating them based on business performance is near impossible. Not good if you&#39;re an IT person and like money.</p>\n</code></pre>\n\n<p>There's other types of comp. then money, obviously, and those are fine too. In particular, we discuss participation in open source and more recognition. But, still: money is the best.</p>",
        "pub_date_ms": 1594980000000,
        "guid_from_rss": "efb05656-d9ef-4fe7-b583-3c49d929fb6c",
        "listennotes_url": "https://www.listennotes.com/e/b03b9f59a5df4d31bf44e1828353c8e6/",
        "audio_length_sec": 3057,
        "explicit_content": true,
        "maybe_audio_invalid": false,
        "listennotes_edit_url": "https://www.listennotes.com/e/b03b9f59a5df4d31bf44e1828353c8e6/#edit"
      },
      {
        "id": "653da187c8fc4d17adee39ecc64e0658",
        "link": null,
        "audio": "https://www.listennotes.com/e/p/653da187c8fc4d17adee39ecc64e0658/",
        "image": "https://production.listennotes.com/podcasts/she-did-it-her-way/sdh-476-im-doing-it-my-way-gZBesUx8hH_-OUp-kAj5It7.1400x1400.jpg",
        "title": "SDH 476: I'm Doing It My Way (Special Announcement) with Amanda Boleyn",
        "podcast": {
          "id": "baf59c165baf441d881b39ec3cc1f320",
          "image": "https://production.listennotes.com/podcasts/she-did-it-her-way-amanda-boleyn-m7n-RzQBvEC-jsD5bCh1vo2.1400x1400.jpg",
          "title": "She Did It Her Way",
          "publisher": "Amanda Boleyn ",
          "thumbnail": "https://production.listennotes.com/podcasts/she-did-it-her-way-amanda-boleyn-ck2Y4SdwDM1-jsD5bCh1vo2.300x300.jpg",
          "listen_score": 47,
          "listennotes_url": "https://www.listennotes.com/c/baf59c165baf441d881b39ec3cc1f320/",
          "listen_score_global_rank": "1%"
        },
        "thumbnail": "https://production.listennotes.com/podcasts/she-did-it-her-way/sdh-476-im-doing-it-my-way-36NVPdTkKzI-OUp-kAj5It7.300x300.jpg",
        "description": "<p>Hello my beautiful listeners! Welcome back to another episode of the She Did It Her Way podcast. This episode is going to be a little bit different in that I have some news to share and I am going to do it in a very full-circle way, joined by my very first podcast guest ever and dear friend, Shauna VanBogart.</p><p>This news has been some time in the making and while it certainly is bittersweet and definitely not the easiest to share it’s important to remember that sometimes the things that aren’t the easiest are actually the most necessary. </p><p>The purpose of having Shauna on the show is that she will actually be interviewing me and pulling some things out of me, as opposed to me being on the other side of the mic, so to speak. </p><p>I hope that this episode gives you permission to pivot, or potentially close a chapter that no longer feels aligned with you, no matter how challenging the transition may be. Especially when you know, in your gut, that it's time for a change.</p><p>As always, my beautiful friends, keep doing it your way. <br /> </p><p> </p><h2><strong>Insights:</strong></h2><ul><li><i>“Oh, she’s gonna do this.”</i></li><li><i>“Go inward. Stay out of your head. Stay in your heart and your gut.”</i></li></ul><p> </p><h2><strong>Resources:</strong></h2><ul><li>Check out how you can use <a href=\"https://shediditherway.com/podia\">Podia</a> in your business</li><li>Get more info about working with <a href=\"https://shaunavanbogart.com\">Shauna VanBogart</a></li></ul>",
        "pub_date_ms": 1640001600000,
        "guid_from_rss": "4ba9006a-73e0-4e78-969e-251495a7bd44",
        "listennotes_url": "https://www.listennotes.com/e/653da187c8fc4d17adee39ecc64e0658/",
        "audio_length_sec": 3002,
        "explicit_content": false,
        "maybe_audio_invalid": false,
        "listennotes_edit_url": "https://www.listennotes.com/e/653da187c8fc4d17adee39ecc64e0658/#edit"
      }
    ]
    const {recommendations} = await fetcher(`/podcasts/${params.id}/recommendations`)
    const dataEP = await fetcher(`/episodes/${searchParams.episode_id}/recommendations`)

console.log("herecome sht the sao n",params,searchParams)
  return (
    <Box height={"75vh"} overflow={"scroll"} p={"18px"}>
        <RecomendationList data={searchParams.episode_id ? dataEP.recommendations:[]} episode={true} />
        <RecomendationList data={recommendations}/>
    </Box>
  )
}

export default Recommendations